### ISSUE TITLE
Add twtiter/facebook social card so this looks more catchy when sharing

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/remote#14]
Just thinking about tweeting this out -- would be nice if we added the social card so this shared well on social media?

**Comment by benhylau** [comment]
For Twitter, https://github.com/hyphacoop/remote/settings we need a **1280×640px** image.

I started https://docs.google.com/presentation/d/1IliHGIBK-1pG94LEp4cOBv6yHoDQm2Fa2qWGUut-uBU/edit#slide=id.g7ec9b071cc_0_0 and can use as a template for all our sites that are for sharing.

![Social_Media_Cards_March2020](https://user-images.githubusercontent.com/2261308/77535988-e2116b00-6e9b-11ea-92b6-fdbb6a51f408.png)

Alternatively we can do a screencap of actual site.

**Comment by benhylau** [comment]
Talked with @dcwalk and here's the updated one we'll use:

![hyphacoop-covid19](https://user-images.githubusercontent.com/2261308/77559767-da15f300-6ebc-11ea-96ae-1de4a93ca7b0.png)

**Comment by benhylau** [comment]
Added to site
