### ISSUE TITLE
Translate to Spanish

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/remote#16]
Translate text to Spanish and present as `es` tab on website. Future changes on `en` will be tracked on this issue to stay in sync.

- [x] Initial translated copy
- [x] Publish on website
- Revisions:
  - [x] https://github.com/hyphacoop/remote/pull/12/files => #18 
  - [x] https://github.com/hyphacoop/remote/pull/15/files => #18 
  - [x] https://github.com/hyphacoop/remote/pull/17/files
  - [x] https://github.com/hyphacoop/remote/pull/19/files => #20 #22 
  - [ ] https://github.com/hyphacoop/remote/pull/21/files
  - [ ] https://github.com/hyphacoop/remote/pull/24/files

_Translation by @llunaCreixent_

**Comment by llunaCreixent** [comment]
Translated with the support of @benhylau and @fadelkon. Thank you very much :)

**Comment by benhylau** [comment]
Thank you!!

**Comment by benhylau** [comment]
Hey @fadelkon have you had a chance to look through #18? I think you're the only capable reviewer here other than the @llunaCreixent the translator :)

Thank you both again for this!

**Comment by benhylau** [comment]
@llunaCreixent I think https://github.com/hyphacoop/remote/pull/15/files isn't in yet, it just got merged.

**Comment by benhylau** [comment]
@dcwalk @uditvira 

Looks like @fadelkon already had a read. Can we merge #18 as is to get things moving, and if #15 hasn't been incorporated we will do as a separate patch?

**Comment by benhylau** [comment]
#15 translations added

**Comment by benhylau** [comment]
New update to English text added to top

**Comment by fadelkon** [comment]
I can take it!

**Comment by llunaCreixent** [comment]
> I can take it!

Me too, let's work together :)

**Comment by benhylau** [comment]
Damnit I wanted to take it 😿

**Comment by fadelkon** [comment]
hahhaha sorry @benhylau !  You can try the other way around next time, from foreign language to native. The result is better and you can learn words, common structures... But hey! You can do it anyway and compare with @llunaCreixent 's help!
